
GameBundle\Entity\Game:
    type: entity
    table: game
    id:
        id:
            type: integer
            generator: {strategy:AUTO}
    fields:
        nameRoom:
            type: string
            lenght: 50
        Score:
            type: integer
            scale: 10
        nbPlayer:
            type: integer
            scale: 2
        saveGame:
            type: string
            lenght: 255
        date:
            type: datetime
            nullable: true
        idUser:
            type: integer
            scale:  11

