GameBundle\Entity\User:
    type: entity
    table: user
    id:
        id:
            type: integer
            generator: {strategy:AUTO}
    fields:
        pseudo:
            type: string
            lenght: 15
        password:
            type: string
            length: 15
        email:
            type: string
            lenght: 255
